### PR TITLE
If we pass an issue number to the action use it in the analysis

### PR DESCRIPTION
**Pull request by petecheslock**
In this example I'm adding a new action parameter we can pass to the analyze action to give it the issue number it should comment on.  

If i'm reading this right, if issueNumber is undefined [here in action-utils](https://github.com/getappmap/action-utils/blob/main/src/Commenter.ts#L18-L28) then `Commenter.issueNumber()` will get the issue number from the github action payload.  This is the current thing that happens and if the action was triggered by a PR then `Commenter.issueNumber()` will contain the correct issue number to comment on.  

I would use [this code](https://github.com/land-of-apps/rails-7-app/blob/26897f6ad85be83b5a42cb5f75643ea22c8c3d9f/searchPullRequest.js) to search for an issue/PR with the HEAD commit and pass it to [the action.](https://github.com/land-of-apps/rails-7-app/blob/main/.github/workflows/analyze-maps-from-circleci.yml#L97-L103)

So then in the action we can check and see if the issue number was set - if it wasn't then set the constant to undefined.  Then when we call `const commenter = new Commenter(octokit, 'appmap', issueNumber);` if `issueNumber is undefined then the [action-utils code](https://github.com/getappmap/action-utils/blob/main/src/Commenter.ts#L18-L28) will get the correct one just as it does today.

### CODE REVIEW

**Comment by kgilpin** [comment]
Have you been able to try this out? You can use a branch of a GitHub action.

**Comment by petecheslock** [comment]
Doing some testing now - here's the first test - running against this branch but not setting the issue number
This PR i've deleted the existing comment https://github.com/land-of-apps/rails-7-app/pull/14
Set the workflow to use this branch https://github.com/land-of-apps/rails-7-app/actions/runs/7200301365/workflow#L114-L119
The comment gets added as normal. 
 https://github.com/land-of-apps/rails-7-app/actions/runs/7200301365/job/19614034566#step:7:40

So the existing functionality works.  testing the new updated functionality.

**Comment by petecheslock** [comment]
Ok - latest test

on this PR: https://github.com/land-of-apps/rails-7-app/pull/20
And using this workflow file: https://github.com/land-of-apps/rails-7-app/blob/main/.github/workflows/analyze-maps-from-circleci.yml

The analysis function uses this branch and passes in the name of the issue as a parameter.
https://github.com/land-of-apps/rails-7-app/blob/main/.github/workflows/analyze-maps-from-circleci.yml#L109-L115

Then when you commit to the pull request branch the CircleCI job runs, does the build, copies the maps to S3 then runs a follow on task which calls the GH action via a webhook.   

The workflow job ran - the Issue number was identified from [this javascript code](https://github.com/land-of-apps/rails-7-app/blob/main/searchPullRequest.js) and that issue number was passed to the action. And the comment was sucessfully applied.  
https://github.com/land-of-apps/rails-7-app/pull/20#issuecomment-1854673615

**Comment by kgilpin** [comment]
Looks good to me! Feel free to merge.

**Pull request merged**
